### ISSUE TITLE
permission denied from repository when trying to install this

### ISSUE THREAD

**Issue by pedramsaleh** [ForceDotComLabs/react.force.datacontainer#2]
I get the following errors when trying to install this using the provided command (npm install git+ssh://git@github.com:ForceDotComLabs/react.force.datacontainer.git --save), with and without sudo. Is it publicly readable?

npm ERR! Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by ivanbogdanov** [comment]
which version of npm are you using?

**Comment by pedramsaleh** [comment]
3.10.3

It seems to install without ssh though using:
rnpm install https://github.com/ForceDotComLabs/react.force.datacontainer.git

**Comment by ivanbogdanov** [comment]
great! are you unblocked now?

**Comment by pedramsaleh** [comment]
Yeah looks to be OK now. Didn't use the library yet but I imported it in my code error free so it should be OK.
I got the same error for other libraries (e.g. react.force) so the ssh command seems to be the issue across the board.

**Comment by ivanbogdanov** [comment]
I made a quick fix for now. Let me know if you see any issues. Thank you for your feedback

**Comment by pedramsaleh** [comment]
It still gives the same error if I use the SSH method currently listed in the readme, but if I use the non-ssh method I mentioned above it's OK.

**Comment by ivanbogdanov** [comment]
Got it. Planning to update readme today. Thank you! You can use https://github.com/ForceDotComLabs/dreamhouse-mobile-react as reference
